modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/Nosey/issues"
license="MIT"

[[mods]]
modId="nosey"
version="${file.jarVersion}"
displayName="Nosey"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nosey"
authors="Mrbysco"
description='''
Do you smell what I'm cooking?
'''
[[dependencies.nosey]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"