modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/Nosey/issues"
license="MIT"

[[mods]]
modId="nosey"
version="${file.jarVersion}"
displayName="Nosey"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nosey"
authors="Mrbysco"
description='''
Do you smell what I'm cooking?
'''
[[dependencies.nosey]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21.4,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.nosey]]
modId="neoforge"
type="REQUIRED"
versionRange="[21.4.0-beta,)"
ordering="NONE"
side="BOTH"